export const techJobsnow = [
    'Node',
    'JavaScript',
    'React',
    'Java',
    'Spring',
    'Python',
    'Django',
    'Flask',
    'Ruby',
    'Rails',
    'PHP',
    'Laravel',
    'C#',
    'C++',
    '.NET',
    'Angular',
    'Vue',
    'TypeScript',
    'Swift',
    'Kotlin',
    'Docker',
];
localStorage.setItem('techKeywords', JSON.stringify(techJobsnow));
